sonar.projectKey=jcontiero_oficina-k8s-infra
sonar.organization=jcontiero

sonar.projectName=oficina-k8s-infra
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.terraform/**,**/node_modules/**
sonar.sourceEncoding=UTF-8

# Ignora falsos positivos de regras no sonar: SHA de actions e regras informativas de Terraform
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=terraform:*
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.tf
